# Generated by Django 3.1.7 on 2021-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('nid', models.CharField(max_length=10)),
                ('p_vac', models.CharField(choices=[('MODERNA', 'MODERNA'), ('SINOPHARM', 'SINOPHARM'), ('PFIZER', 'PFIZER'), ('ASTRAZENECA', 'ASTRAZENECA')], default='SINOPHARM', max_length=50)),
                ('a_vac', models.CharField(choices=[('MODERNA', 'MODERNA'), ('SINOPHARM', 'SINOPHARM'), ('PFIZER', 'PFIZER'), ('ASTRAZENECA', 'ASTRAZENECA')], default='SINOPHARM', max_length=50)),
                ('appointment', models.CharField(default='Not Selected for VAC', max_length=60)),
                ('vaced', models.BooleanField(default=False)),
            ],
        ),
    ]
