# Generated by Django 3.1.7 on 2021-09-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covapp', '0003_auto_20210903_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineregistration',
            name='nid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
