# Generated by Django 3.1.7 on 2021-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covapp', '0004_auto_20210903_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(max_length=255)),
            ],
        ),
    ]
